version: '3'

services:

  symfony:
    ports:
      - 8080:80
    image: registry.gitlab.com/aroha-docker/symfony/5.4/dev:latest
    environment:
      PROJECT_CODE: 'api'
    volumes:
      - .:/var/www/html
      - var_cache:/var/www/html/var/cache
      - composer_cache:/root/.composer
    depends_on:
      - mysql
      - redis
      - mailhog

  mysql:
    image: mariadb:10.7
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    depends_on:
      - mysql
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "3"

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "3"

  redis:
    image: redis:6
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "3"

volumes:
  composer_cache:
  var_cache:
